In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a=np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14,5,7,18],dtype="float32")

array([ 3.14,  5.  ,  7.  , 18.  ], dtype=float32)

In [8]:
np.array([3.14,5,7,18],dtype="int")

array([ 3,  5,  7, 18])

In [ ]:
# sifirdan array 

In [9]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
import numpy as np
a=np.random.randint(10,size=(5,5))
a

array([[1, 0, 9, 2, 7],
       [2, 8, 7, 3, 8],
       [6, 9, 5, 5, 3],
       [7, 3, 1, 0, 6],
       [5, 0, 6, 8, 2]])

In [12]:
import numpy as np
a=np.random.randint(10,size=(3,4))
a

array([[8, 1, 1, 9],
       [1, 1, 5, 4],
       [8, 8, 1, 3]])

In [13]:
alt_a=a[0:3,0:4]
alt_a

array([[8, 1, 1, 9],
       [1, 1, 5, 4],
       [8, 8, 1, 3]])

In [14]:
alt_a[0,0]=9999
alt_a[1,1]=888
alt_a

array([[9999,    1,    1,    9],
       [   1,  888,    5,    4],
       [   8,    8,    1,    3]])

In [15]:
a

array([[9999,    1,    1,    9],
       [   1,  888,    5,    4],
       [   8,    8,    1,    3]])

In [19]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [23]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [25]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
np.random.normal(10,4,(3,4))

array([[ 7.15451684,  4.64986624,  6.62282128, 10.85289069],
       [11.63972165, 11.63180885, 11.06934271, 17.82112021],
       [ 8.73306334, 14.23031321,  7.17394591, 13.80153407]])

In [28]:
np.random.randint(0,10,(3,3))

array([[7, 5, 9],
       [4, 2, 8],
       [9, 0, 5]])

#Özellikleri

* **ndim: _boyut sayısı
* **shape: _boyut bilgisi
* **size: _toplam eleman sayısı
* **dtype:_array veri tipi

In [29]:
import numpy as np

In [30]:
np.random.randint(10,size=10)

array([7, 5, 5, 2, 9, 7, 7, 2, 5, 5])

In [31]:
a=np.random.randint(10,size=10)

In [32]:
a.ndim

1

In [33]:
a.shape

(10,)

In [34]:
a.size

10

In [35]:
a.dtype

dtype('int32')

In [36]:
b=np.random.randint(10,size=(3,5))

In [37]:
b

array([[8, 5, 2, 3, 5],
       [1, 8, 7, 2, 8],
       [3, 0, 9, 1, 1]])

In [38]:
b.ndim

2

In [39]:
b.size

15

In [40]:
b.shape

(3, 5)

In [41]:
b.dtype

dtype('int32')

In [42]:
import numpy as np

In [ ]:
#yeniden şekilllendirme

In [43]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a=np.arange(1,10)

In [48]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
 a.ndim

1

In [58]:
b=a.reshape((1,9))

In [59]:
b.ndim

2

In [60]:
import numpy as np

In [62]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [64]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [65]:
z=np.array([7,8,9])

In [66]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
#iki boyut

In [68]:
a= np.array([[1,2,3],
             [4,5,6]])

In [69]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [72]:
#ayırma:split

In [73]:
import numpy as np

In [76]:
x=np.array([1,2,3,99,99,3,2,1])

In [77]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [78]:
a,b,c=np.split(x,[3,5])

In [80]:
a

array([1, 2, 3])

In [81]:
b

array([99, 99])

In [82]:
c

array([3, 2, 1])

In [83]:
#iki noyutlu ayırma

In [84]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [86]:
ust,alt=np.vsplit(m,[2])

In [87]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [88]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [91]:
sag,sol=np.hsplit(m,[2])

In [92]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [93]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [94]:
v=np.array([2,1,4,3,5])

In [95]:
v

array([2, 1, 4, 3, 5])

In [96]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [97]:
v

array([2, 1, 4, 3, 5])

In [100]:
v.sort()

In [101]:
v

array([1, 2, 3, 4, 5])

In [102]:
#iki boyutlu array sıralama

In [104]:
m=np.random.normal(20,5,(3,3))

In [105]:
m

array([[22.1875294 , 23.8239246 , 21.19283699],
       [27.90766021, 24.74319906, 17.01447553],
       [29.65165362, 25.22298151, 14.82245793]])

In [106]:
np.sort(m,axis=1)

array([[21.19283699, 22.1875294 , 23.8239246 ],
       [17.01447553, 24.74319906, 27.90766021],
       [14.82245793, 25.22298151, 29.65165362]])

In [107]:
np.sort(m,axis=0)

array([[22.1875294 , 23.8239246 , 14.82245793],
       [27.90766021, 24.74319906, 17.01447553],
       [29.65165362, 25.22298151, 21.19283699]])

In [108]:
a=np.random.randint(10,size=10)
a

array([5, 5, 5, 8, 3, 5, 9, 6, 7, 1])

In [109]:
a[]

SyntaxError: invalid syntax (<ipython-input-109-f195c1342970>, line 1)

In [110]:
a[0]

5

In [111]:
a[-1]

1

In [112]:
a[0]=100

In [113]:
a

array([100,   5,   5,   8,   3,   5,   9,   6,   7,   1])

In [114]:
m=np.random.randint(10,size=(3,5))

In [115]:
m

array([[1, 0, 8, 8, 3],
       [2, 4, 6, 0, 2],
       [2, 7, 7, 0, 7]])

In [116]:
m[0,0]

1

In [117]:
m[1,1]

4

In [120]:
m[2,4]

7

m[0,5]=100

In [121]:
m


array([[1, 0, 8, 8, 3],
       [2, 4, 6, 0, 2],
       [2, 7, 7, 0, 7]])

In [122]:
m[0,5]=100

IndexError: index 5 is out of bounds for axis 1 with size 5

In [123]:
m[0,4]=100


In [124]:
m

array([[  1,   0,   8,   8, 100],
       [  2,   4,   6,   0,   2],
       [  2,   7,   7,   0,   7]])

In [125]:
m[1,1]=2.2

In [126]:
m

array([[  1,   0,   8,   8, 100],
       [  2,   2,   6,   0,   2],
       [  2,   7,   7,   0,   7]])

In [127]:
a=np.arange(20,30)

In [128]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [129]:
a[0:3]

array([20, 21, 22])

In [130]:
a[:3]

array([20, 21, 22])

In [131]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [132]:
a[1::2]

array([21, 23, 25, 27, 29])

In [133]:
a[0::2]

array([20, 22, 24, 26, 28])

In [134]:
a[0::]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [135]:
a[0::3]

array([20, 23, 26, 29])

In [136]:
#iki b slice


In [137]:
m=np.random.randint(10,size=(5,5))

In [138]:
m

array([[5, 0, 0, 4, 9],
       [5, 6, 1, 8, 8],
       [3, 5, 8, 6, 8],
       [8, 5, 1, 1, 5],
       [5, 8, 6, 3, 6]])

In [139]:
m[:,0]

array([5, 5, 3, 8, 5])

In [141]:
m[0,:]

array([5, 0, 0, 4, 9])

In [142]:
m[1,:]

array([5, 6, 1, 8, 8])

In [143]:
m[0:2,0:3]

array([[5, 0, 0],
       [5, 6, 1]])

In [144]:
m[::,:2]

array([[5, 0],
       [5, 6],
       [3, 5],
       [8, 5],
       [5, 8]])

In [145]:
m[::,0:2]

array([[5, 0],
       [5, 6],
       [3, 5],
       [8, 5],
       [5, 8]])

In [146]:
m[1:3,0:2]

array([[5, 6],
       [3, 5]])

In [147]:
m

array([[5, 0, 0, 4, 9],
       [5, 6, 1, 8, 8],
       [3, 5, 8, 6, 8],
       [8, 5, 1, 1, 5],
       [5, 8, 6, 3, 6]])

In [149]:
a=np.random.randint(10,size=(5,5))
a

array([[5, 1, 4, 2, 6],
       [2, 8, 7, 8, 3],
       [8, 3, 2, 4, 6],
       [1, 7, 5, 5, 9],
       [6, 1, 8, 1, 5]])

In [150]:
alt_a=a[0:3,0:2]
alt_a

array([[5, 1],
       [2, 8],
       [8, 3]])

In [155]:
alt_a[0,0]=9999
alt_a[1,1]=888


In [156]:
alt_a

array([[9999,    1],
       [   2,  888],
       [   8,    3]])

In [158]:
m=np.random.randint(10,size=(5,5))

In [159]:
m


array([[0, 2, 8, 8, 3],
       [7, 0, 8, 4, 2],
       [2, 1, 3, 1, 0],
       [3, 5, 1, 9, 2],
       [5, 8, 2, 7, 7]])

In [160]:
alt_b=m[0:3,0:2].copy()

In [161]:
alt_b

array([[0, 2],
       [7, 0],
       [2, 1]])

In [162]:
alt_b[0,0]=999

In [163]:
alt_b

array([[999,   2],
       [  7,   0],
       [  2,   1]])

In [164]:
m

array([[0, 2, 8, 8, 3],
       [7, 0, 8, 4, 2],
       [2, 1, 3, 1, 0],
       [3, 5, 1, 9, 2],
       [5, 8, 2, 7, 7]])

In [165]:
alt_b*3

array([[2997,    6],
       [  21,    0],
       [   6,    3]])

In [166]:
#fancy index


In [167]:
v=np.arange(0,30,3)

In [168]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [169]:
v[1]

3

In [170]:
v[3]

9

In [171]:
v[5]

15

In [172]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [173]:
al_getir=[1,3,5]

In [174]:
v[al_getir]

array([ 3,  9, 15])

In [175]:
#iki boyutta fancy

In [176]:
m=np.arange(9).reshape((3,3))

In [177]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [178]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [179]:
m[satir,sutun]

array([1, 5])

In [180]:
m[0,[1,2]]

array([1, 2])

In [181]:
#slice ile fancy


In [182]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [184]:
v=np.array([1,2,3,4,5])

In [185]:
v>5

array([False, False, False, False, False])

In [186]:
v<5

array([ True,  True,  True,  True, False])

In [187]:
v>3

array([False, False, False,  True,  True])

In [188]:
v<3

array([ True,  True, False, False, False])

In [189]:
v[v<3]

array([1, 2])

In [190]:
v[v>3]

array([4, 5])

In [191]:
v[v>=3]

array([3, 4, 5])

In [192]:
v[v<=3]

array([1, 2, 3])

In [193]:
v[v!=2]

array([1, 3, 4, 5])

In [194]:
v[v==4]

array([4])

In [195]:
v*2


array([ 2,  4,  6,  8, 10])

In [196]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [197]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [198]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [199]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [200]:
v-1

array([0, 1, 2, 3, 4])

In [201]:
v*5

array([ 5, 10, 15, 20, 25])

In [ ]:
#ufunc

In [202]:
np.subtract(v,1)


array([0, 1, 2, 3, 4])

In [203]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [204]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [205]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [206]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [207]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [208]:
np.absolute([np.array([-3])])

array([[3]])

In [209]:
np.sin(360)

0.9589157234143065

In [210]:
np.cos(180)

-0.5984600690578581

In [211]:
v=np.array([1,2,3])

In [212]:
v

array([1, 2, 3])

In [213]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [215]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [216]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [217]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\seevv\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\seevv\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

In [218]:
#cheatsheet


In [219]:
#istatiksel hesap

In [222]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [220]:
v.sum()

6

In [224]:
#NUMPY İLE 2 BİLİNMEYENLİ DENKLEM

5*x0+x1=12
x0+3*x1=10


In [227]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [228]:
a

array([[5, 1],
       [1, 3]])

In [229]:
b

array([12, 10])

In [230]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])